// Array of course objects
const Courses = [
	{
		name: 'Full Stack Web Development with Node',
		rating: 5,
		price: 512100,
		duration: 9,
		tutor: 'Dafe Stanley',
		whatToLearn: [
			'HTML',
			'CSS',
			'Javascript',
			'MySQL',
			'NodeJS',
			'Express',
			'MongoDB',
			'UX/UI Design Concept',
		],
		desc: '',
	},
	{
		name: 'Front-End Development with Angular.JS',
		rating: 5,
		price: 284500,
		duration: 5,
		tutor: 'Dafe Stanley',
		whatToLearn: [
			'HTML',
			'Javascript',
			'CSS',
			'Angular',
			'JQuery & AJAX',
			'UX/UI Design Concept',
		],
		desc: '',
	},
	{
		name: 'Data Analytics with Excel and Power BI',
		rating: 5,
		price: 75250,
		duration: 2,
		tutor: 'Dafe Stanley',
		whatToLearn: [
			'Excel',
			'Microsoft Power BI',
			'Database',
			'Datasource',
			'Advanced Excel',
			'Data Modelling & Desing',
			'Data Visualization with Power BI',
		],
		desc: '',
	},
	{
		name: 'UI/UX Design',
		rating: 5,
		price: 170700,
		duration: 3,
		tutor: 'Dafe Stanley',
		whatToLearn: [
			'HTML & CSS',
			'Prototyping',
			'Ideation / Brainstorming',
			'Design Thinking',
			'Sketching and Wireframing',
			'User Research',
			'Introduction to UX Design',
		],
		desc: '',
	},
	{
		name: 'Full Stack Web Development with Python',
		rating: 5,
		price: 512100,
		duration: 9,
		tutor: 'Dafe Stanley',
		whatToLearn: [
			'HTML',
			'CSS',
			'MongoDB',
			'MySQL',
			'React',
			'Javascript',
			'Python',
			'Django',
		],
		desc: '',
	},
	{
		name: 'Android App Development',
		rating: 5,
		price: 170700,
		duration: 3,
		tutor: 'Dafe Stanley',
		whatToLearn: [
			'Kotlin',
			'Dart',
			'Flutter',
			'Database(SQLite)',
			'Introduction to Android App Development',
			'App Design Concept',
			'Firebase',
		],
		desc: '',
	},
];

export default Courses;
